'''
exceptions.py: exceptions defined by textform

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2020-2022 by the California Institute of Technology.  This code
is open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''


# Base class.
# .............................................................................
# The base class makes it possible to use a single test to distinguish between
# exceptions generated by Documentarist code and exceptions generated by
# something else.

class DocumentaristException(Exception):
    '''Base class for Documentarist exceptions.'''
    pass


# Exception classes.
# .............................................................................

class CannotProceed(DocumentaristException):
    '''A recognizable condition caused an early exit from the program.'''
    pass

class UserCancelled(DocumentaristException):
    '''The user elected to cancel/quit the program.'''
    pass

class CorruptedContent(DocumentaristException):
    '''Content corruption has been detected.'''
    pass

class InternalError(DocumentaristException):
    '''Unrecoverable problem involving textform itself.'''
    pass

class FileError(DocumentaristException):
    '''Problem reading or writing a file or its attributes.'''
    pass
